### PR TITLE
run the health server before newManager

### PR DESCRIPTION
**Pull request by zhiweiyin318**
Signed-off-by: Zhiwei Yin <zyin@redhat.com>

### CODE REVIEW

**Comment by qiujian16** [comment]
@zhiweiyin318 should this be cherry-picked?

**Comment by zhiweiyin318** [comment]
@qiujian16 let me open cherry-pick PRs and wait until the issue is approved to fix into 2.4 and 2.5.

/cherry-pick release-2.5
/cherry-pick release-2.4

**Pull request merged**
